# Generated by Django 2.1.7 on 2019-03-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=30)),
                ('password_plain', models.CharField(max_length=30)),
                ('alias', models.CharField(max_length=30)),
                ('avatar', models.TextField()),
                ('student_validation', models.BooleanField(default=False)),
                ('student_id', models.CharField(max_length=20)),
                ('validated_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
                ('commit_stamp', models.DateTimeField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('abstract', models.CharField(max_length=200)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bubbles.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_stamp', models.DateTimeField()),
                ('content', models.TextField()),
                ('master_bubble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubbles.Bubble')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bubbles.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='bubble',
            name='tags',
            field=models.ManyToManyField(to='bubbles.Tag'),
        ),
    ]
