# Generated by Django 2.1.7 on 2019-03-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='student_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='validated_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
