# Generated by Django 2.1.7 on 2019-03-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bubbles', '0002_auto_20190309_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='access_restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='publish_restriction',
            field=models.BooleanField(default=False),
        ),
    ]
